# Generated by Django 3.2.6 on 2021-09-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='E_name',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
