# Generated by Django 3.2.7 on 2021-09-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_student_e_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='E_name',
            field=models.CharField(max_length=100),
        ),
    ]
