# Generated by Django 3.2.7 on 2021-09-21 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_student_e_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='event',
            table=None,
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
